baseURL: https://www.stpaulchenoa.org
title: St. Paul Ev. Lutheran Church

params:
  description: St. Paul Evangelical Lutheran Church of Chenoa Illinois

menu:
  main:
  - name: Home
    url: /
    weight: 1

  - name: News
    url: /news
    weight: 2

  - name: Calendar
    url: /calendar/
    weight: 3

  - name: Contact
    url: /contact/
    weight: 4

  social:
  - name: Facebook
    pre: <i class="fa-brands fa-facebook"></i>
    url: https://www.facebook.com/stpaulchenoa/
    weight: 1

  - name: YouTube
    pre: <i class="fa-brands fa-youtube"></i>
    url: https://www.youtube.com/channel/UCzVEAM5iyYBCMmrROt_0uPg
    weight: 2